version: 2

jobs:
  deploy-stage:
    docker:
      - image: circleci/python:3.7.3-stretch
    working_directory: /tmp/stage-deployment
    steps:
      - checkout
      - run:
          name: Build stage
          command: |
            cd website
            npm install
            npm run build
      - run:
          name: Deploy to S3
          command: |
            virtualenv ~/sdk
            source ~/sdk/bin/activate
            pip install awscli --upgrade
            aws s3 sync $WEBSITE_BUILD_DIR $AWS_S3_STAGE_BUCKET --acl public-read

workflows:
  version: 2
  stage-deployment:
    jobs:
      - deploy-stage